---    
 - name: Play For Installing apache2 on ubuntu
   hosts: Web 
   become: yes  
   tasks:  
    - name: Install apache2 
      apt:
        name: apache2
        state: present 
    - name: Start apache2 Service
      service:
        name: apache2
        state: started
    

